### PR TITLE
add thumbs file

### PR DESCRIPTION
**Pull request by davidx**
This adds a .thumbs.yml file.

### CODE REVIEW

**Comment by lukebakken** [comment]
I'll switch the port used for testing the HTTP API, one second.

**Comment by jbrisbin** [comment]
We probably also want `merge: true` so that Thumbs can merge things for us, right @lukebakken?

**Comment by lukebakken** [comment]
@davidx @jbrisbin if thumbs merges what gets recorded in the merge commit?

**Comment by lukebakken** [comment]
👍

**Comment by davidx** [comment]
@lukebakken here's an example on riak_ql: https://github.com/basho/riak_ql/commit/21d2ad23d5b9b7cc1b8456814693d0f3d1029695

Open to suggestions on including more useful info in the merge commit if needed.
thanks!

**Comment by davidx** [comment]
@jbrisbin @lukebakken did you want me to update the pr with merge:true ? just thought it'd start out without automerge until you guys were comfortable with it.

**Comment by lukebakken** [comment]
Doesn't matter to me, really. I like clicking the merge button.

**Comment by davidx** [comment]
:)

**Comment by jbrisbin** [comment]
I'm curious about the flow of using automerge, but it doesn't matter to me. If @lukebakken wants to keep it manual I'm fine with that too.

Either way, 👍

**Pull request merged**
